### ISSUE TITLE
once project scafoled, what do we do ?

### ISSUE THREAD

**Issue by benavern** [harisvsulaiman/valk#1]
Hi,

I have to say I am very enthousiast for such a project.
I just tried it and after scaffolding my app what do we have to do ? 
I tried `meson build` but I had this error:
```
The Meson build system
Version: 0.44.0
Source dir: /home/zezen/Workspace/elementary/zomnifer
Build dir: /home/zezen/Workspace/elementary/zomnifer/build
Build type: native build

Meson encountered an error in file meson.build, line 40, column 26:
Method name must be plain id
    dependency(gobject-2.0),
                          ^

A full log can be found at /home/zezen/Workspace/elementary/zomnifer/build/meson-logs/meson-log.txt

```
Could you tell me or/and wright in the readme or/and add it when the scaffolding is success, what to do there ?

Thanks in advance :)

**Comment by peteruithoven** [comment]
Looks like the dependencies are missing `"`'s. 
https://github.com/harisvsulaiman/valk/blob/master/vala/generators.js#L70

**Comment by benavern** [comment]
Wow, very reactive! thanks. But its 3 O'Clock now, I'll look at this tomorrow. 
Hope you'll make this project a must have for elementary apps devs! :)
